### ISSUE TITLE
skip youtube adds

### ISSUE THREAD

**Issue by OrionRandD** [manateelazycat/emacs-application-framework#635]
How do i configure eaf-browser to skip annoying youtube adds?
If this feature is not in eaf,
Please, add it...
Thx.

**Comment by manateelazycat** [comment]
Done by https://github.com/manateelazycat/emacs-application-framework/commit/c529728608d45a92abd7b3dd4a24f8423a591659

**Comment by OrionRandD** [comment]
> Done by [c529728](https://github.com/manateelazycat/emacs-application-framework/commit/c529728608d45a92abd7b3dd4a24f8423a591659)

after "git pull" 
I am still getting those horrible youtube adds   :(

**Comment by manateelazycat** [comment]
restart EAF

**Comment by OrionRandD** [comment]
> restart EAF

Have restarted Emacs twice to no avail...
https://imgur.com/a/peozSmF
down right corner -> pular anuncios -> skip adds

:(

**Comment by OrionRandD** [comment]
> restart EAF
I have removed the folder eaf and I am cloning it again...
Let us see... 
Tomorrow I will test that...

**Comment by OrionRandD** [comment]
> restart EAF

Ok. I have reinstalled eaf and its dependencies.
It seems to work now. The main YT adds disappeared, but still some other kind of adds appear.
I think the bes way to solve this would be you to add support for installing "noScript". 
I have "noScript" in my browsers and I can control which stuff can run or not in my web-pages:
https://noscript.net/
Apart from that, perhaps adding support for opening invidious, instead of Youtube would be great!
https://github.com/iv-org/invidious
I also have a "tampermonkey" script for redirecting youtube videos to invidious instances. 
So that, I get rid of all YT annoyances...
https://www.tampermonkey.net/
If you can add support to install tamppermonkey, so that people can install scripts inside it
Thx a lot anyway for your hard work...
